const arbre = `
Smartphones
	_Système d'exploitation_
		iOS
			Camera
				triple
					Ecran
						oled
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
													iPhone -14.2 Pro Fold
												compact
													iPhone -14 Pro
										capteur
											_Maléabilité_
												pliable
													iPhone -15.2 Pro Fold
												compact
													iPhone -15 Pro
										aucun
											_Maléabilité_
												pliable
													iPhone -16 Pro Fold
												compact
													iPhone 16 Pro
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
						amoled
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
						ips
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
				double
					Ecran
						oled
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
													iPhone -14.2 Fold
												compact
													iPhone -14
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
						amoled
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
						ips
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
													iPhone X
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
				simple
					Ecran
						oled
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
						amoled
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
						ips
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
													iPhone 4
										capteur
											_Maléabilité_
												pliable
												compact
													iPhone 7
										aucun
											_Maléabilité_
												pliable
												compact
													iPhone 8
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
		android
			Camera
				triple
					Ecran
						oled
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
													Google Pixel 9 Pro Fold
												compact
													Google Pixel 8 Pro
													Google Pixel 9 Pro
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
						amoled
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
													Samsung Galaxy Z Fold 5
												compact
													Samsung Galaxy S23 Ultra
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
													Samsung Galaxy S23
						ips
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
				double
					Ecran
						oled
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
													Google Pixel 8
													Google Pixel 9
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
						amoled
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
													Samsung Galaxy Z Flip 5
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
													Samsung Galaxy S10
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
						ips
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
				simple
					Ecran
						oled
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
													Samsung Galaxy S9
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
						amoled
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
						ips
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
		windows phone
			Camera
				triple
					Ecran
						oled
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
													Microsoft Windows Teams 5 Fold
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
													Microsoft Geolocalisator Teams 2
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
						amoled
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
						ips
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
				double
					Ecran
						oled
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
													Microsoft Geolocalisator Teams
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
						amoled
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
						ips
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
				simple
					Ecran
						oled
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
						amoled
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
						ips
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
													Lumia 950 XL
													Nokia Lumia 1020
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact`;
