const arbre = `
Smartphones
	_Système d'exploitation_
		iOS
			Camera 
				triple
					Ecran
						oled
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
						amoled
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
						ips
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
				double
					Ecran
						oled
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
						amoled
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
						ips
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
				simple
					Ecran
						oled
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
						amoled
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
						ips
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
		android
			Camera 
				triple
					Ecran
						oled
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
						amoled
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
						ips
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
				double
					Ecran
						oled
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
						amoled
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
						ips
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
				simple
					Ecran
						oled
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
						amoled
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
						ips
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
		windows phone
			Camera 
				triple
					Ecran
						oled
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
						amoled
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
						ips
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
				double
					Ecran
						oled
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
						amoled
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
						ips
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
				simple
					Ecran
						oled
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
						amoled
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
						ips
							Rafraichissement
								120Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								60Hz
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact
								modulable
									Bouton central
										poussoir
											_Maléabilité_
												pliable
												compact
										capteur
											_Maléabilité_
												pliable
												compact
										aucun
											_Maléabilité_
												pliable
												compact`;
